FROM node:18.5.0

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY ./src ./src
COPY ./public ./public

CMD npx wait-port metadata:80 && \
    npx wait-port history:80 && \
    npm start